int puts(int a);
int calloc(int a, int b);
int free(int a);
int malloc(int a);
int memset(int a, int b, int c);
int realloc(int a, int b);
int strlen(int a);
int strcpy(int a, int b);
int close(int a);
int open(int a, int b);
int memmove(int a, int b, int c);
int strcmp(int a, int b);
int snprintf(int a, int b, int c, int d);
int memcpy(int a, int b, int c);
int fwrite(int a, int b, int c, int d);
int fputc(int a, int b);
int unlink(int a);
int fopen(int a, int b);
int fclose(int a);
int memcmp(int a, int b, int c);
int sprintf(int a, int b, int c);
int read(int a, int b, int c);
