int acv_i(int o);
int alloc_sec_names(int s1, int strsec);
int args_parser_add_file(int s, int filename, int filetype);
int asym_next(int o);
int asym_prev_tok(int o);
int atks_hash_next(int o);
int atks_sym_identifier(int o);
int ats_files(int o);
int ats_nb_files(int o);
int ats_nb_priv_sections(int o);
int ats_nb_sections(int o);
int ats_priv_sections(int o);
int ats_sections(int o);
int begin_macro(int str, int alloc);
int block(int bsym, int csym, int is_expr);
int convert_parameter_type(int pt);
int cstr_cat(int cstr, int str, int len);
int cstr_ccat(int cstr, int ch);
int cstr_free(int cstr);
int cstr_new(int cstr);
int cstr_realloc(int cstr, int new_size);
int cstr_reset(int cstr);
int decl0(int l, int is_for_loop_init, int func_sym);
int decl_initializer(int type, int sec, int c, int first, int size_only);
int decl(int l);
int dynarray_add(int ptab, int nb_ptr, int data);
int dynarray_reset(int pp, int n);
int elf_hash(int name);
int elf_output_file(int s1, int filename);
int elfsym(int s);
int ELFW_R_INFO(int sym, int type);
int ELFW_R_SYM(int val);
int ELFW_R_TYPE(int val);
int ELFW_ST_BIND(int val);
int ELFW_ST_INFO(int bind, int type);
int ELFW_ST_TYPE(int val);
int ELFW_ST_VISIBILITY(int o);
int end_macro();
int enter();
int expr_eq();
int external_global_sym(int v, int type, int r);
int external_sym(int v, int type, int r, int ad);
int find_elf_sym(int s, int name);
int free_section(int s);
int gadd_sp(int val);
int gad_f_func_type(int o);
int gad_section(int o);
int gbf_buf_end(int o);
int gbf_buffer(int o);
int gbf_buf_ptr(int o);
int gbf_fd(int o);
int gbf_filename(int o);
int gbf_line_num(int o);
int gbf_prev(int o);
int gcall_or_jmp(int is_jmp);
int gcs_data(int o);
int gcs_size_allocated(int o);
int gcs_size(int o);
int gct_ref(int o);
int gct_t(int o);
int gcv_i(int o);
int gcv_str_data(int o);
int gcv_str_size(int o);
int gcv_tab(int o);
int gee_e_ident(int o);
int gee_e_shoff(int o);
int gen_addr32(int r, int sym, int c);
int gen_assign_cast(int dt);
int gen_cast(int type);
int gen_function(int sym);
int gen_le32(int c);
int gen_modrm(int op_reg, int r, int sym, int c);
int gen_opic(int op);
int gen_opi(int op);
int gen_op(int op);
int ger_r_info(int o);
int ger_r_offset(int o);
int ges_st_info(int o);
int ges_st_name(int o);
int ges_st_other(int o);
int ges_st_shndx(int o);
int ges_st_size(int o);
int ges_st_value(int o);
int get_reg(int rc);
int get_sym_ref(int type, int sec, int offset, int size);
int get_tok_str(int v, int cv);
int gexpr();
int gfs_name(int o);
int gfs_type(int o);
int gfunc_call(int nb_args);
int gfunc_epilog();
int gfunc_param_typed(int func, int arg);
int gfunc_prolog(int func_type);
int gfunc_return(int func_type);
int g(int c);
int gjmp2(int instr,int lbl);
int gjmp_addr(int a);
int gjmp(int t);
int global_identifier_push(int v, int t, int c);
int greloca(int s, int sym, int offset, int type, int addend);
int greloc(int s, int sym, int offset, int type);
int gs_data_allocated(int o);
int gs_data(int o);
int gs_data_offset(int o);
int gs_hash(int o);
int gs_link(int o);
int gs_name(int o);
int gs_nb_hashed_syms(int o);
int gs_reloc(int o);
int gs_sh_addralign(int o);
int gs_sh_addr(int o);
int gs_sh_entsize(int o);
int gs_sh_flags(int o);
int gs_sh_info(int o);
int gs_sh_name(int o);
int gs_sh_num(int o);
int gs_sh_offset(int o);
int gs_sh_size(int o);
int gs_sh_type(int o);
int gsv_c(int o);
int gsv_r(int o);
int gsv_sym(int o);
int gsv_type(int o);
int gsym_addr(int t, int a);
int gsym_c(int o);
int gsym_f_func_type(int o);
int gsym(int t);
int gsym_next(int o);
int gsym_prev(int o);
int gsym_prev_tok(int o);
int gsym_r(int o);
int gsym_sym_scope(int o);
int gsym_type(int o);
int gsym_v(int o);
int gtks_hash_next(int o);
int gtks_len(int o);
int gtks_str(int o);
int gtks_sym_identifier(int o);
int gtkst_allocated_len(int o);
int gtkst_alloc(int o);
int gtkst_lastlen(int o);
int gtkst_len(int o);
int gtks_tok(int o);
int gtkst_prev(int o);
int gtkst_prev_ptr(int o);
int gtkst_str(int o);
int gto_flags(int o);
int gto_index(int o);
int gto_name(int o);
int gts_files(int o);
int gts_filetype(int o);
int gts_nb_files(int o);
int gts_nb_priv_sections(int o);
int gts_nb_sections(int o);
int gts_outfile(int o);
int gts_priv_sections(int o);
int gts_sections(int o);
int gts_symtab(int o);
int gtst(int inv, int t);
int gv(int rc);
int gvtst(int inv, int t);
int handle_eob();
int handle_stray1(int p);
int init_c();
int init_globals();
int init_option(int t,int name, int index, int flags);
int init_options();
int init_putv(int type, int sec, int c);
int init_reg_classes();
int init_runtime();
int isid(int c);
int isnum(int c);
int is_space(int ch);
int leave(int x);
int load(int r, int sv);
int lvalue_type(int t);
int main(int argc0, int argv0);
int mk_pointer(int type);
int new_section(int s1, int name, int sh_type, int sh_flags);
int next();
int next_nomacro();
int next_nomacro1();
int next_nomacro_spc();
int oad(int c, int s);
int o(int c);
int parse_btype(int type, int ad);
int parse_comment(int p);
int parse_escape_string(int outstr, int buf, int is_long);
int parse_number(int p);
int parse_pp_string(int p, int sep, int str);
int parse_string(int s, int len);
int patch_storage(int sym, int ad, int type);
int patch_type(int sym, int type);
int PEEKC_EOB(int c1, int p1);
int PEEKC(int c1, int p1);
int pointed_type(int type);
int post_type(int type, int ad, int storage);
int preprocess_start(int s1, int is_asm);
int pstrcpy(int buf, int buf_size, int s);
int put_elf_str(int s, int sym);
int put_extern_sym(int sym, int section, int value, int size);
int read16le(int p);
int read32le(int p);
int rebuild_hash(int s, int nb_buckets);
int ri16(int o);
int ri32(int o);
int sad_f_func_type(int o, int v);
int save_reg(int r);
int save_regs(int n);
int save_reg_upstack(int r, int n);
int sbf_buf_end(int o, int v);
int sbf_buf_ptr(int o, int v);
int sbf_fd(int o, int v);
int sbf_line_num(int o, int v);
int sbf_prev(int o, int v);
int scs_data(int o, int v);
int scs_size_allocated(int o, int v);
int scs_size(int o, int v);
int sct_ref(int o, int v);
int sct_t(int o, int v);
int scv_i(int o, int v);
int scv_str_data(int o, int v);
int scv_str_size(int o, int v);
int section_add(int sec, int size, int align);
int section_ptr_add(int sec, int size);
int section_realloc(int sec, int new_size);
int section_reserve(int sec, int size);
int see_e_ehsize(int o, int v);
int see_e_machine(int o, int v);
int see_e_shentsize(int o, int v);
int see_e_shnum(int o, int v);
int see_e_shoff(int o, int v);
int see_e_shstrndx(int o, int v);
int see_e_type(int o, int v);
int see_e_version(int o, int v);
int ser_r_info(int o, int v);
int ser_r_offset(int o, int v);
int sesh_sh_addralign(int o, int v);
int sesh_sh_addr(int o, int v);
int sesh_sh_entsize(int o, int v);
int sesh_sh_flags(int o, int v);
int sesh_sh_info(int o, int v);
int sesh_sh_link(int o, int v);
int sesh_sh_name(int o, int v);
int sesh_sh_offset(int o, int v);
int sesh_sh_size(int o, int v);
int sesh_sh_type(int o, int v);
int ses_st_info(int o, int v);
int ses_st_name(int o, int v);
int ses_st_other(int o, int v);
int ses_st_shndx(int o, int v);
int ses_st_size(int o, int v);
int ses_st_value(int o, int v);
int set_idnum(int c, int val);
int sfs_type(int o, int v);
int skip(int c);
int sort_syms(int s1, int s);
int ss_data_allocated(int o, int v);
int ss_data(int o, int v);
int ss_data_offset(int o, int v);
int ss_hash(int o, int v);
int ss_link(int o, int v);
int ss_nb_hashed_syms(int o, int v);
int ss_reloc(int o, int v);
int ss_sh_addralign(int o, int v);
int ss_sh_addr(int o, int v);
int ss_sh_entsize(int o, int v);
int ss_sh_flags(int o, int v);
int ss_sh_info(int o, int v);
int ss_sh_name(int o, int v);
int ss_sh_num(int o, int v);
int ss_sh_offset(int o, int v);
int ss_sh_size(int o, int v);
int ss_sh_type(int o, int v);
int ssv_r(int o, int v);
int ssv_sym(int o, int v);
int ssym_c(int o, int v);
int ssym_f_func_type(int o, int v);
int ssym_next(int o, int v);
int ssym_prev(int o, int v);
int ssym_prev_tok(int o, int v);
int ssym_r(int o, int v);
int ssym_sym_scope(int o, int v);
int ssym_v(int o, int v);
int stks_hash_next(int o, int v);
int stks_len(int o, int v);
int stks_sym_identifier(int o, int v);
int stkst_allocated_len(int o, int v);
int stkst_alloc(int o, int v);
int stkst_lastlen(int o, int v);
int stkst_len(int o, int v);
int stks_tok(int o, int v);
int stkst_prev(int o, int v);
int stkst_prev_ptr(int o, int v);
int stkst_str(int o, int v);
int sto_flags(int o, int v);
int sto_index(int o, int v);
int sto_name(int o, int v);
int store(int r, int v);
int strstart(int val, int str);
int sts_filetype(int o,int v);
int sts_nb_sections(int o,int v);
int sts_outfile(int o,int v);
int sts_symtab(int o,int v);
int sym_find(int v);
int sym_free(int sym);
int __sym_malloc();
int sym_malloc();
int sym_pop(int ptop, int b, int keep);
int sym_push2(int ps, int v, int t, int c);
int sym_push(int v, int type, int r, int c);
int tcc_add_file_internal(int s1, int filename, int flags);
int tcc_add_file(int s, int filename);
int tcc_close();
int tcc_compile(int s1);
int tcc_delete(int s1);
int tccelf_begin_file(int s1);
int tccelf_delete(int s1);
int tccelf_end_file(int s1);
int tccelf_new(int s);
int tcc_free(int ptr);
int tccgen_compile(int s1);
int tcc_malloc(int size);
int tcc_mallocz(int size);
int tcc_new();
int tcc_open_bf(int s1, int filename, int initlen);
int tcc_open(int s1, int filename);
int tcc_output_file(int s, int filename);
int tcc_parse_args(int s, int pargc, int pargv, int optind);
int tccpp_delete(int s);
int tccpp_new(int s);
int tcc_realloc(int ptr, int size);
int tcc_strdup(int str);
int tok_alloc(int str, int len);
int tok_alloc_new(int pts, int str, int len);
int TOK_GET(int t, int pp, int cv);
int TOK_HASH_FUNC(int h, int c);
int tok_str_add2(int s, int t, int cv);
int tok_str_add(int s, int t);
int tok_str_add_tok(int s);
int tok_str_alloc();
int tok_str_free(int str);
int tok_str_free_str(int str);
int tok_str_new(int s);
int tok_str_realloc(int s, int new_size);
int type_decl(int type, int ad, int v);
int type_size(int type, int a);
int unary();
int unget_tok(int last_tok);
int update_storage(int sym);
int v_alloca(int x);
int vpop();
int vpushi(int v);
int vpushsym(int type, int sym);
int vsetc(int type, int r, int vc);
int vset(int type, int r, int v);
int vstore();
int vswap();
int wi16(int o, int v);
int wi32(int o, int v);
int write16le(int p, int x);
int write32le(int p, int x);
int add(int a, int b);
int and(int a, int b);
int div_(int a, int b);
int eq(int a, int b);
int gt(int a, int b);
int gte(int a, int b);
int lt(int a, int b);
int lte(int a, int b);
int mod(int a, int b);
int mul(int a, int b);
int neq(int a, int b);
int or(int a, int b);
int shl(int a, int b);
int shr(int a, int b);
int sub(int a, int b);
int not(int a);
int xor(int a, int b);
int movsx_eax_al(int eax);
int ri8(int o);
int wi8(int o,int v);
int mks(int s);
int mkc(int c);

int new_symtab(int s1, int symtab_name, int sh_type, int sh_flags,
               int strtab_name, int hash_name, int hash_sh_flags);
int set_elf_sym(int s, int value, int size,
                       int info, int other, int shndx, int name);
int put_elf_sym(int s, int value, int size,
    int info, int other, int shndx, int name);
int decl_initializer_alloc(int type, int ad, int r,
                                   int has_init, int v, int scope);
